/**
 * Clinical Report Generation & PDF Service
 * Interfaces with backend report endpoints.
 */

import apiClient from './api';

export interface ReportData {
  case_id: string;
  patient_id: string;
  age: number;
  gender: string;
  screening_date: string;
  location: string;
  healthcare_centre: string;
  worker_name: string;
  status: string;
  original_image_url?: string;
  ai_prediction?: {
    is_fundus: boolean;
    quality_status: string;
    quality_score: number;
    dr_stage?: number;
    severity_name?: string;
    confidence?: number;
    class_probabilities?: Record<string, number>;
    gradcam_url?: string;
    lesion_data?: any[];
    triage_decision: string;
    priority: string;
  };
  doctor_review?: {
    doctor_name: string;
    doctor_reg_number?: string;
    original_dr_stage: number;
    final_dr_stage: number;
    final_severity: string;
    decision_type: string;
    clinical_notes: string;
    treatment_plan?: string;
    follow_up_timeline?: string;
    reviewed_at: string;
  };
  hospital_referral?: {
    hospital_name: string;
    priority: string;
    status: string;
  };
  audit_trail: Array<{
    action: string;
    timestamp: string;
    metadata?: Record<string, any>;
  }>;
  disclaimer: string;
}

export const reportService = {
  /**
   * Fetches structured clinical report data
   */
  async getReportData(caseId: string): Promise<ReportData> {
    const response = await apiClient.get<ReportData>(`/api/v1/reports/${caseId}`);
    return response.data;
  },

  /**
   * Downloads official PDF clinical report generated by backend
   */
  async downloadReportPdf(caseId: string): Promise<void> {
    const response = await apiClient.get(`/api/v1/reports/${caseId}/pdf`, {
      responseType: 'blob',
    });

    const blob = new Blob([response.data], { type: 'application/pdf' });
    const downloadUrl = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.download = `RuralDR_Report_${caseId}.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(downloadUrl);
  },
};
